# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8dff69f85ad9a0a7e936ae38272f399d572b5bab66b03f0531ec26546d525d603573f5e199ca0c002b140b0546dadd2b73f9368e715a7d06647a2d4a10be925c

test:
  secret_key_base: 1080e48db96fb83e08eb561b7143079eb3d64f1480f79931398e66bb975354ce4d0b68635ec9e2fc1902d9b2354e9355b31ef38e4517155955be81cef1fcdde9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
